In [2]:
import numpy as np

In [3]:
a = np.array([[2,2],[2,2],[1,1],[1,2]])

In [12]:
a


array([[2, 2],
       [2, 2],
       [1, 1],
       [1, 2]])

In [18]:
a[:,1]

array([2, 2, 1, 2])

In [11]:
a
a[(1,2,3,0),1]

array([2, 1, 2, 2])

In [95]:
b = np.array([[0,1],[0,1]])
b

array([[0, 1],
       [0, 1]])

In [96]:
(a[0]-b)**2

array([[4, 1],
       [4, 1]])

In [151]:
c = np.sum(b**2,axis=1, keepdims=1)
c

array([[1],
       [1]])

In [152]:
d = np.reshape(c,(2,1)) 
d

array([[1],
       [1]])

In [153]:
d + np.array([8,8,2,5])

array([[9, 9, 3, 6],
       [9, 9, 3, 6]])

In [132]:
c + np.array([8,8,2,5]) - np.dot(b,a.T)

array([[6, 6, 1, 3],
       [7, 7, 2, 4]])

In [130]:
np.dot(b,a.T)

array([[2, 2, 1, 2],
       [2, 2, 1, 2]])

In [17]:
np.sqrt(np.sum((a-b)**2))

4.0

In [21]:
a.shape[0]

3

In [135]:
a
np.sum(a**2, axis = 1)

array([8, 8, 2, 5])

In [28]:
l = []

In [29]:
v = [1,2,3,4]

In [30]:
l.append(v)
l

[[1, 2, 3, 4]]

In [31]:
for i in range(len(v)):
    l.append(v[i])
l

[[1, 2, 3, 4], 1, 2, 3, 4]

In [52]:
a = {'1':2, '2':4, '3':1, '4':4}

In [39]:
max(a.values())

4

In [44]:
for elem in a:
    print(a.get(elem))

4
2
1


In [55]:
[x for x, v in a.items() if v == 2]

['1']

In [57]:
np.argsort(v)

array([0, 1, 2, 3])

In [154]:
l = ['a','b','c']

In [8]:
l[:-3]

NameError: name 'l' is not defined

In [61]:
c = np.zeros((3,3))

aux = tuple(range(y.shape[0]))
c, y, aux

(array([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]), array([2, 0, 1]), (0, 1, 2))

In [55]:
for x in enumerate(y):
    print(x)

(0, 2)
(1, 0)
(2, 1)


In [62]:
c[y, aux] = 1
c

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]])

In [66]:
y = np.array([1,2,0])
c[np.arange(3),y].reshape(-1,1)

array([[ 1.],
       [ 1.],
       [ 1.]])

In [70]:
np.sum(a,axis = 1)

array([4, 4, 2, 3])